base_path: /data/rsourave/datasets/Coutrot
batch_size: 6
epochs: 10
length: 2
lr: 0.001
model_type: 1
shuffle: true
stride: 10
videos:
- 1
- 11
- 3
viewers:
- 0
- 3
output_dir: /data/rsourave/saved_models/Coutrot/
