base_path: /data/rsourave/datasets/EGTEA
batch_size: 6
epochs: 10
length: 1
lr: 0.001
model_type: 0
shuffle: true
stride: 32
videos:
- 4
- 5
- 6
- 8
- 9
- 10
- 11
- 12
- 14
- 15
- 16
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 7
- 50
- 37
- 45
- 13
- 17
- 29
- 35
- 64
- 18
- 56
- 61
viewers:
- 0
output_dir: /data/rsourave/saved_models/EGTEA/

